In [1]:
import numpy as np

### 作业1：

1. 生成一个3行5列的数组，元素值从1到15排列  
2. 取出其中的第1行，第3列元素  
3. 取出其中的第2行到最后一行  
4. 取出其中的第1行到第2行，第1列到最后一列  
5. 取出其中的第0行和第2行，第三列  

In [113]:
arr = np.arange(1, 16).reshape(3, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [115]:
arr[1, 3]

9

In [116]:
arr[2:]

array([[11, 12, 13, 14, 15]])

In [117]:
arr[1:3, 1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [118]:
arr[[0, 2], 3]

array([ 4, 14])

## 作业4-2：  

给出一组学生姓名，和他们对应的成绩，存储在下方数组中。请计算以下问题：  
找出不及格的学生姓名（提示：使用布尔型索引）  
找出最高分、最低分，平均分数  
将数值成绩转化成字母成绩，大于等于90分为A， 70-89分为B，小于70分为C  

In [99]:
names = np.array(["Xiao Ming","Xiao Zhang","Xiao Gang","Xiao Hong","Xiao Pang","Xiao Wu","Xiao Dai",
                  "Xiao Qian","Xiao Fan","Xiao Wang"])
scores = np.array([ 91,  68,  84,  55,  95,  81,  67,  82,  86,  78])

In [120]:
mask = scores < 60
print(names[mask])
print(scores[mask])

['Xiao Hong']
[55]


In [122]:
print(scores.max())
print(scores.mean())
print(scores.min())
print(scores.var())
print(scores.std())

95
78.7
55
132.81
11.5243221059


### 方法1

In [109]:
rank = []
for score in scores:
    if score >= 90:
        rank.append('A')
    elif score > 70:
        rank.append('B')
    else:
        rank.append('C')
        
rank

['A', 'C', 'B', 'C', 'A', 'B', 'C', 'B', 'B', 'B']

### 方法2

In [110]:
['A' if score >= 90 else 'B' if score > 70 else 'C' for score in scores]

['A', 'C', 'B', 'C', 'A', 'B', 'C', 'B', 'B', 'B']

### 方法3

In [123]:
np.where(scores >= 90, 'A', np.where(scores>=70, 'B', 'C'))

array(['A', 'C', 'B', 'C', 'A', 'B', 'C', 'B', 'B', 'B'], 
      dtype='<U1')

In [125]:
scores_2 = np.array([92, 80, 66])
np.where(scores_2>90, 'A', np.where(scores_2>=70, 'B', 'C'))

array(['A', 'B', 'C'], 
      dtype='<U1')

In [132]:
np.where([True, False, False], ['A', 'A', 'A'], ['B', 'B', 'C'])

array(['A', 'B', 'C'], 
      dtype='<U1')